<?php
 // module/Users/view/users/upload/index.phtml:

 $title = 'Uploads for '.$user->name;
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
     <a href="<?php echo $this->url('users/upload-manager', array('action'=>'add'));?>">>> Upload a File</a>
 <table class="table">
 <tr>
     <th>Label</th>
     <th>Filename</th>
     <th>Action</th>
 </tr>
 <?php foreach ($myUploads as $upload) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($upload->label);?></td>
     <td><?php echo $this->escapeHtml($upload->filename);?></td>
     <td>
       <a href="<?php echo $this->url('users/upload-manager',array('action'=>'edit', 'id' => $upload->id));?>">Edit</a> | 
       <a href="<?php echo $this->url('users/upload-manager',array('action'=>'delete', 'id' => $upload->id));?>"  onclick="return confirm('Are you sure?')">Delete</a>
     </td>
  </tr>
 <?php endforeach; ?>
 </table>
 
 <h2>Shared Uploads</h2>

<table class="table">
<tr>
    <th>Label</th>
    <th>Filename</th>
    <th>Shared By</th> 
</tr>
<?php foreach ($sharedUploadsList as $uploadId => $upload) : ?>
<tr>
    <td><?php echo $this->escapeHtml($upload['label']);?></td>
    <td><a href="<?php echo $this->escapeHtml($this->url('users/upload-manager',
            array('action'=>'fileDownload', 'id' => $uploadId)));?>">Download</a> </td>
    <td><?php echo $this->escapeHtml(join(";",$upload['sharedUsers']));?></td>    
</tr>
<?php endforeach; ?>
</table>