<?php
// Attached jQuery UI Scripts
$this->headScript ()->appendFile ( 'js/jquery-1.8.3.js', 'text/javascript' );
$this->headScript ()->appendFile ( 'js/jquery-ui.js', 'text/javascript' );
// Attach jQuery UI Styles
$this->headLink ()->appendStylesheet ( '/css/jquery-ui.css' );
//
$this->headScript ()->appendScript ( '$(function() {$( "#btnRefresh" ).click(function( event ) {document.getElementById("messageListFrame").contentWindow.location.reload(true);})
										});', 'text/javascript' );
$this->headScript ()->appendScript ('setInterval(refreshIframe, 5000);
									function refreshIframe() { document.getElementById("messageListFrame").contentWindow.location.reload(true); }',
									 'text/javascript' );
$this->headStyle ()->appendStyle ( '#userName { width:100px; margin-top:10px; display: inline} #messageText { width:700px; margin-top:10px;}' );
?>
<h3>Group Chat</h3>
<iframe	src="<?php echo $this->url ( 'users/group-chat', array ('action' => 'messageList' 	) )?>"
	width="80%" height="400px" id="messageListFrame"></iframe>
<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(NULL, array('controller'=>'GroupChat', 'action' => 'index')));
$form->setAttribute('method', 'post');
// Render the opening tag
echo $this->form ()->openTag ( $form );
// ...loop through and render the form elements...
echo '<label id="userName">' . $userName . ': </label>';
foreach ( $form as $element ) {
	echo $this->formElement ( $element ); // <-- Magic!
	echo $this->formElementErrors ( $element );
}
// Render the closing tag
echo $this->form ()->closeTag ();
?>


